// @flow
const CHANGE_BOX_VALUE = 'CHANGE_BOX_VALUE'
const CLEAR_PUZZLE = 'CLEAR_PUZZLE'
const SOLVE_PUZZLE = 'SOLVE_PUZZLE'
const UNDO_MOVE = 'UNDO_MOVE'

export { CHANGE_BOX_VALUE, CLEAR_PUZZLE, SOLVE_PUZZLE, UNDO_MOVE }
